language: cpp
cache: ccache
dist: bionic
compiler: g++
sudo: false
addons:
  apt:
    packages:
      - g++-multilib
      - gcc-multilib
      - libcurl4-openssl-dev
      - libboost-python-dev
      - python3-dev
      - curl
script:
    - make TRAVIS=1

after_deploy:
    - zip -r artifacts-x64.zip vkbotlite src/*.o
    - curl --upload-file ./artifacts-x64.zip https://transfer.sh/artifacts-x64.zip > output
    - cat output

