language: c++
cache: ccache
compiler: g++
sudo: false
addons:
  apt:
    packages:
      - git
      - g++
      - make
      - libcurl4-openssl-dev
      - libgd-dev
      - libboost-python-dev
      - python3-dev
      - zip
      - curl
script:
    - make TRAVIS=1; fi
    - zip -r artifacts.zip vkbotlite src/*.o; fi
    - curl --upload-file ./artifacts.zip https://transfer.sh/artifacts.zip; fi
