language: cpp
cache: ccache
dist: bionic
compiler: g++
sudo: false
addons:
  apt:
    packages:
      - git
      - g++
      - g++-multilib
      - gcc-multilib
      - make
      - libcurl4-openssl-dev
      - libgd-dev
      - libboost-python-dev
      - python3-dev
      - zip
      - curl
script:
    - make TRAVIS=1
    - zip -r artifacts-x86.zip vkbotlite src/*.o
    - curl --upload-file ./artifacts-x86.zip https://transfer.sh/artifacts-x86.zip
