language: cpp
cache: ccache
dist: xenial
compiler: g++
sudo: false
addons:
  apt:
    packages:
      - git
      - g++-multilib
      - gcc-multilib
      - libcurl4-openssl-dev
      - libgd-dev
      - libboost-python-dev
      - python3-dev
      - curl
script:
    - make TRAVIS=1

after_deploy:
    - zip -r artifacts-x86.zip vkbotlite src/*.o
    - curl --upload-file ./artifacts-x86.zip https://transfer.sh/artifacts-x86.zip

