print('python3 modules init')
#     cmd      path    disp info cost acess
init('i', 'example.py', 1, 'статистика бота', 0, 1)
init('cl', 'clean.py', 5, 'очистить все сообщения от бота за последние 24 часа', 0, 5)
init('маста', 'ms_xash.py', 1, 'парсинг мастер сервера xash3d', 0, 1)
init('k', 'kick.py', 0, 'random', 0, 2)
init('a', 'add.py', 0, 'random', 0, 2)
init('лурк', 'lurk.py', 1, 'поиск по лурку', 0, 1)
init('chat', 'chat.py', 1, 'статистика чата', 0, 1)
init('allchats', 'allchats.py', 1, 'статистика всех чатов в которых есть бот', 0, 5)
init('вики', 'wiki_ru.py', 1, 'ru.wikipedia.org', 0, 1)
init('wiki', 'wiki_en.py', 1, 'en.wikipedia.org', 0, 1)
init('online', 'online.py', 1, 'онлайн чата', 0, 1)
init('scr', 'scr.py', 1, 'скриншот сайта', 0, 1)
